#================================ Kafka ================================#
#List of Kafka brokers
broker:
    - host: localhost
      port: 9092

#=========================== Schema Registry ===========================#
#List of Schema Registry instances
schema_registry:
    host: localhost
    port: 8081
    protocol: http
#=========================== Rest Proxy  ===============================#
# if the producer_mode is rest, you must provide rest_proxy values
rest_proxy:
    host: localhost
    port: 8082
    protocol: http

#Possible value are direct or rest
producer_mode: rest

#number_of_devices: 1

data:
  - topic: android_empatica_e4_acceleration
    sensor: ACCELEROMETER
    frequency: 32.0
    file: accelerometer.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4Acceleration
    assert_header: "x, y, z"
  - topic: android_empatica_e4_battery_level
    sensor: BATTERY_LEVEL
    frequency: 1.0
    file: battery.csv
    key_schema: org.radarcns.key.MeasurementKey
    value_schema: org.radarcns.empatica.EmpaticaE4BatteryLevel
    assert_header: "batteryLevel"
#  - topic: android_empatica_e4_blood_volume_pulse
#    sensor: BLOOD_VOLUME_PULSE
#    frequency: 64.0
#    file: blood_volume_pulse.csv
#    key_schema: org.radarcns.key.MeasurementKey
#    value_schema: org.radarcns.empatica.EmpaticaE4BloodVolumePulse
#  - topic: android_empatica_e4_electrodermal_activity
#    sensor: ELECTRODERMAL_ACTIVITY
#    frequency: 4.0
#    file: electrodermal_activity.csv
#    key_schema: org.radarcns.key.MeasurementKey
#    value_schema: org.radarcns.empatica.EmpaticaE4ElectroDermalActivity
#  - topic: android_empatica_e4_inter_beat_interval
#    sensor: INTER_BEAT_INTERVAL
#    frequency: 1.0
#    file: inter_beat_interval.csv
#    key_schema: org.radarcns.key.MeasurementKey
#    value_schema: org.radarcns.empatica.EmpaticaE4InterBeatInterval
#  - topic: android_empatica_e4_temperature
#    sensor: THERMOMETER
#    frequency: 4.0
#    file: thermometer.csv
#    key_schema: org.radarcns.key.MeasurementKey
#    value_schema: org.radarcns.empatica.EmpaticaE4Temperature